# Generated by Django 3.0.5 on 2020-10-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polle',
            name='voters',
            field=models.ManyToManyField(default=None, to='acount.Account'),
        ),
    ]
